- block:

  # Software
  - import_tasks: software/repositories.yml
  - import_tasks: software/apt.yml
  - import_tasks: software/packages_development.yml
  - import_tasks: software/packages_utilities.yml


  # Users
  - import_tasks: users/root.yml
  - import_tasks: users/docker.yml


  # System
  - import_tasks: systemSetup/clock.yml
  - import_tasks: systemSetup/locale.yml
