- name: system setup | repositories | add sources.list for debian hosts
  tags: non-free,repositories
  copy:
    src: distro_source/debian_sources.list
    dest: /etc/apt/sources.list
    backup: yes


- name: system setup | repositories | install package management tools (debian-based)
  tags: packages,system,settings
  package:
    name:
      #- aptitude
      - software-properties-common
    state: latest
